# env
@url=https://webpack.uz/api
@admin-key=Admin9204
@admin-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlNldmluY2hiZWsgVGF4aXJvdiIsInVzZXJuYW1lIjoic2FhZHRha2hpciIsInBob25lIjoiKzk5ODkwNTc4OTIwNCIsImlhdCI6MTcwMjgyMDQ4NSwiZXhwIjoxNzAzNDI1Mjg1fQ.JjRk3QOKUNcjeImMYs6fXqGSh_2yreTE0zc6YAeUpdI
@waiter-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6IlNhYWQgVGFraGlyIiwidXNlcm5hbWUiOiJ0YXhpcm92IiwicGhvbmUiOiIrOTk4OTE5MTIzMTg3IiwiaWF0IjoxNzAxMjgwMTkyLCJleHAiOjE3MDE4ODQ5OTJ9.3x10cyqX-qHq93Z4ej0V8bGM_v-His4Ede_koUgqED8

### test role apis
# get all roles
GET {{url}}/role
###
# post role
POST {{url}}/role
Admin-Key: {{admin-key}}
Content-Type: application/json

{ "name": "waiter" }

###
# put role
PUT {{url}}/role/3
Admin-Key: {{admin-key}}
Content-Type: application/json

{ "name": "chef"}
###
# delete role
DELETE {{url}}/role/3
Admin-Key: {{admin-key}}
###
---------------------------------------------------------------------------------------
###
# get all users
GET {{url}}/user
Access-Token: {{admin-token}}

###
# register user
POST {{url}}/user/register
Admin-Key: {{admin-key}}
Content-Type: application/json

{
    "name": "Saad Takhir",
    "username": "taxirov",
    "password": "Saad1234",
    "salary": 3000000,
    "role_id": 2,
    "phone": "+998919123187",
    "email": "saadtakhir1@gmail.com",
    "joined_date": "24.11.2023T23:20:10Z"
}
###
# login user
POST {{url}}/user/login
Content-Type: application/json

{
    "username": "saadtakhir",
    "password": "Saad1234"
}

###
# get admin verify
GET {{url}}/user/admin
Admin-Key: {{admin-key}}

###
# get token verify
GET {{url}}/user/verify
Access-Token: {{waiter-token}}
###
# delete user
DELETE {{url}}/user/6
Admin-Key: {{admin-key}}
Access-Token: {{admin-token}}
###
# put user
PUT {{url}}/user/7
Admin-Key: {{admin-key}}
Access-Token: {{admin-token}}
Content-Type: application/json

{
    "name": "Bobur Toxirov",
    "username": "toxirov_bobur",
    "salary": 6000000,
    "role_id": 2,
    "phone": "+998919123187",
    "email": "toxirovbobur@gmail.com"
}
###
------------------------------------------------------------------------
###
# get room
GET {{url}}/room
Access-Token: {{admin-token}}
###
# post room
POST {{url}}/room
Admin-Key: {{admin-key}}
Access-Token: {{admin-token}}
Content-Type: application/json

{
    "name": "Zal 2",
    "desc": "izoh zal 2",
    "capacity": 30,
    "created_date": "2023-11-28T21:55:17.418Z"
}
###
# put room
PUT {{url}}/room/2
Admin-Key: {{admin-key}}
Access-Token: {{admin-token}}
Content-Type: application/json

{
    "name": "Zal 2",
    "desc": "izoh zal 2",
    "capacity": 10,
    "created_date": "2023-11-28T21:55:17.418Z"
}
###
# delete room
DELETE {{url}}/room/2
Admin-Key: {{admin-key}}
Access-Token: {{admin-token}}
###
# get room by id
GET {{url}}/room/1
Access-Token: {{admin-token}}
###

# get category
GET {{url}}/category
Access-Token: {{admin-token}}
###
# post category
POST {{url}}/category
Access-Token: {{admin-token}}
Admin-Key: {{admin-key}}
Content-Type: application/json

{
    "name": "Waters",
    "desc": "izoh waters",
    "created_date": "2023-11-28T21:55:17.418Z"
}
###
# delete category
DELETE {{url}}/category/1
Admin-Key: {{admin-key}}
###
# put category
PUT {{url}}/category/2
Admin-Key: {{admin-key}}
Content-Type: application/json

{
    "name": "Breads",
    "desc": "izoh breads"
}
###
----------------------------------------------------------------------------------
###

# get product
GET {{url}}/product
###
# post product
POST {{url}}/product
Admin-Key: {{admin-key}}
Content-Type: application/json

{
    "name": "fanta 1.5",
    "category_id": 1,
    "desc": "izoh cola 1.5",
    "created_date": "2023-11-28T21:55:17.418Z",
    "price": 6000
}
###
# delete product
DELETE {{url}}/product/2
Admin-Key: {{admin-key}}
###
# put product
PUT {{url}}/product/1
Admin-Key: {{admin-key}}
Content-Type: application/json

{
    "name": "fanta 0.5",
    "category_id": 3,
    "desc": "izoh cola 1.5",
    "price": 6000
}
###

# post order
POST {{url}}/order
Access-Token: {{admin-token}}
Content-Type: application/json

{
    "title": "Order 23",
    "desc": "order 2 izoh",
    "room_id": null,
    "created_date": "2023-11-28T21:55:17.418Z"
}
###
# put order
PUT {{url}}/order/1
Content-Type: application/json
Access-Token: {{admin-token}}

{ "title": "Order 3", "desc": "order 3 izoh", "user_id": 1, "room_id": null }
###
# get all order
DELETE {{url}}/order/3
Access-Token: {{admin-token}}
Admin-Key: {{admin-key}}
###
# get orders
GET {{url}}/order?&current_page=1&per_page=12
Access-Token: {{admin-token}}
###
# patch order status
PATCH {{url}}/order/4/status
Access-Token: {{admin-token}}
Content-Type: application/json

{
    "status": 0
}
###

# get product in order
GET {{url}}/productinorder
Access-Token: {{admin-token}}
###
# post product in order
POST {{url}}/productinorder
Access-Token: {{admin-token}}
Content-Type: application/json

{
    "order_id": 4,
    "product_id": 1,
    "count": 2,
    "created_date": "2023-11-28T21:55:17.418Z"
}
###
# patch product in order status
PATCH {{url}}/productinorder/4/status
Access-Token: {{admin-token}}
Content-Type: application/json

{
    "status": 1
}
###
# delete pro
